#!/bin/bash

## Shell Opts ----------------------------------------------------------------
set -exuo pipefail
IFS=$'\n\t'


## Vars -----------------------------
GITDIR=/root/github/autojump


## Main ----------------------------------------------------------------------

# Install -------------------------------------------------------------
if [[ ! -d $GITDIR ]]; then
    git clone git://github.com/joelthelion/autojump.git $GITDIR
fi

cd $GITDIR 
./install.py
echo '[[ -s /root/.autojump/etc/profile.d/autojump.sh ]] && source /root/.autojump/etc/profile.d/autojump.sh' >> ~/.bashrc
echo "Autojump installed successfully!"
