#!/bin/bash

## Shell Opts ----------------------------------------------------------------
set -exuo pipefail
IFS=$'\n\t'


## Vars -----------------------------
GITDIR=/root/github/autojump


## Main ----------------------------------------------------------------------

# Install -------------------------------------------------------------
yum groupinstall -y "Development tools"
yum install -y ncurses-devel ncurses-libs zlib-devel mysql-devel bzip2-devel \
               openssl-devel ncurses-devel  readline-devel tk-devel gdbm-devel\
               db4-devel libpcap-devel xz-devel openssl-devel sqlite-devel \
               uuid-devel libffi-devel libuuid-devel

if [[ ! -d $GITDIR ]]; then
    git clone git://github.com/joelthelion/autojump.git $GITDIR
fi

cd $GITDIR 
./install.py
echo "Python$VERSION installed successfully!"
