#!/bin/bash

## Shell Opts ----------------------------------------------------------------
set -exuo pipefail
IFS=$'\n\t'
tempdir=$(mktemp -d)
trap "rm -rf $tempdir" EXIT


## Main ----------------------------------------------------------------------
# Check the version of current Python3
if [[ -n `python3 --version | grep -P "Python 3\.[6-9]"` ]]
then
echo 'Python>=3.6 already satisfied'
    exit 0  # Exit if version is 3.6
fi


# Install -------------------------------------------------------------
cd $tempdir
wget https://github.com/kelseyhightower/confd/releases/download/v0.16.0/confd-0.16.0-linux-amd64
mkdir -p /opt/confd/bin
mv confd-0.16.0-linux-amd64 /opt/confd/bin/confd
chmod +x /opt/confd/bin/confd
export PATH="$PATH:/opt/confd/bin"


echo 'Confd installed successfully!'

