#!/usr/bin/bash

### Shell Opts ----------------------------------------- 
set -xeuo pipefail
tempdir=$(mktemp -d) 
trap "rm -rf $tempdir" EXIT
IFS=$'\n\t'

### Main ----------------------------------------------------
if [[ `which crudini` ]]
then
    exit 0
fi


git clone --depth 1 https://github.com/pixelb/crudini.git $tempdir
cp $tempdir/crudini /usr/bin/crudini
chmod +x /usr/bin/crudini
