#!/usr/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ `which crudini` ]]
then
    exit 0
fi

if [[ -e /tmp/crudini ]]
then 
    rm -rf /tmp/crudini
fi

git clone https://github.com/pixelb/crudini.git /tmp/crudini
cp /tmp/crudini/crudini /usr/bin/crudini
chmod +x /usr/bin/crudini
