#!/usr/bin/bash
tempdir="/tmp/crudini.$$"
trap "rm -rf $tempdir" EXIT
set -xeuo pipefail
IFS=$'\n\t'

if [[ `which crudini` ]]
then
    exit 0
fi


git clone --depth 1 https://github.com/pixelb/crudini.git $tempdir
cp $tempdir/crudini /usr/bin/crudini
chmod +x /usr/bin/crudini
