#!/usr/bin/bash

## Shell Opts ------------------------------------
set -exuo pipefail

## Main -----------------------------------------
# Uninstall old version
yum remove -y docker \
              docker-client \
              docker-client-latest \
              docker-common \
              docker-latest \
              docker-latest-logrotate \
              docker-logrotate \
              docker-selinux \
              docker-engine-selinux \
              docker-engine

# Install using the repository
yum install -y yum-utils \
  device-mapper-persistent-data \
  lvm2
yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

yum install -y docker-ce

# Start docker daemon
systemctl enable docker
systemctl start docker

echo 'Docker installed successfully!'

