#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Check the version of current Python3
echo `python3 --version` | grep "Python 3.6"
if [[ $? -eq 0 ]]
then
    exit 0  # Exit if version is 3.6
fi

# Install
yum groupinstall -y "Development tools"
yum install -y ncurses-devel ncurses-libs zlib-devel mysql-devel bzip2-devel \
               openssl-devel ncurses-devel  readline-devel tk-devel gdbm-devel\
               db4-devel libpcap-devel xz-devel openssl-devel
wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz -O /tmp/Python-3.6.4.tar.xz
cd /tmp 
tar xvJf Python-3.6.4.tar.xz && cd Python-3.6.4
./configure --prefix=/usr
make
make install
