#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Make sure any git on this compute.
if [[ ! `which git` ]]
then
    yum -y install git
fi

# Check the version of current git.
set +e
echo `git --version` | grep -P '2\.[1-9][0-9]'
if [[ $? -eq 0 ]]
then
    exit 0 #  Exit if version >= 2.10
fi 
set -e


# Install git via git.
if [[ -e '/tmp/git' ]]
then
    rm -rf /tmp/git
fi
git clone -d 1 https://github.com/git/git /tmp/git
cd /tmp/git
# Install dependencies 
yum install -y curl-devel openssl-devel
make prefix=/usr
make install prefix=/usr
