#!/bin/bash

## Shell Opts -----------------------------------------------------
set -xeuo pipefail
IFS=$'\n\t'

## Main -----------------------------------------------------
# Make sure any git on this compute.
if [[ ! `which git` ]]
then
    yum -y install git
fi

# Check the version of current git.
set +e
echo `git --version` | grep -P '2\.[1-9][0-9]'
if [[ $? -eq 0 ]]
then
    exit 0 #  Exit if version >= 2.10
fi 
set -e


# Install git via git.
if [[ $# == 1 ]]; then
    tempdir=$1
else
    tempdir=$HOME/github/git
    git clone --depth 1 https://github.com/git/git $tempdir
fi

cd $tempdir
# Install dependencies 
yum install -y curl-devel openssl-devel expat-devel
make prefix=/usr
make install prefix=/usr

echo 'Git installed successfully!'
