#!/bin/bash

## Shell Opts -----------------------------------------------------
set -xeuo pipefail
IFS=$'\n\t'
tempdir=$(mktemp -d)
trap "rm -rf $tempdir" EXIT

## Main -----------------------------------------------------
cd $tempdir
wget https://nodejs.org/dist/latest/node-v10.4.0.tar.gz
cd node-v8.11.1
./configure
make
make install 
echo 'NodeJS installed successfully!'