#!/bin/bash

## Shell Opts ----------------------------------------------------------------
set -exuo pipefail
IFS=$'\n\t'





# Install -------------------------------------------------------------
wget https://rpmfind.net/linux/fedora/linux/releases/27/Everything/x86_64/os/Packages/o/openssl-devel-1.1.0f-9.fc27.x86_64.rpm
wget http://rpmfind.net/linux/fedora/linux/releases/27/Everything/x86_64/os/Packages/o/openssl-1.1.0f-9.fc27.x86_64.rpm