#!/bin/bash

## Shell Opts ----------------------------------------------------------------
set -exuo pipefail
IFS=$'\n\t'
tempdir=$(mktemp -d)
trap "rm -rf $tempdir" EXIT

## Vars -----------------------------
VERSION=$1
if [[ $VERSION != "3.6" && $VERSION != "3.7" ]]; then
    echo "版本号选择 3.6/3.7"
    exit 1
fi


## Main ----------------------------------------------------------------------
# Check the version of current Python3
if [[ -n `python3 --version | grep -P "Python $VERSION"` ]]
then
echo "Python=$VERSION already satisfied"
    exit 0  # Exit if version is 3.6
fi


# Install -------------------------------------------------------------
yum groupinstall -y "Development tools"
yum install -y ncurses-devel ncurses-libs zlib-devel mysql-devel bzip2-devel \
               openssl-devel ncurses-devel  readline-devel tk-devel gdbm-devel\
               db4-devel libpcap-devel xz-devel openssl-devel sqlite-devel \
               uuid-devel libffi-devel libuuid-devel

git clone -b $VERSION --depth 1 https://github.com/python/cpython.git $tempdir

cd $tempdir 
./configure --prefix=/usr
make
make install
echo "Python$VERSION installed successfully!"