#!/bin/bash
# This works on both CentOS 7 and 6

## Shell Opts ----------------------------------------------------------------
set -exuo pipefail
IFS=$'\n\t'

## Main ----------------------------------------------------------------------
yum install -y transmission-cli transmission-common transmission-daemon
if [[ -n `which systemctl 2>/dev/null` ]]
then
    systemctl enable transmission-daemon
    systemctl start transmission-daemon
else
    /etc/init.d/transmission-daemon start
    chkconfig transmission-daemon on
fi
